"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.Deal = exports.Lead = exports.Listing = exports.PropertyType = exports.AdminUnit = exports.Agent = exports.UserRole = exports.Role = exports.User = exports.BaseEntity = void 0;
var base_entity_1 = require("./base.entity");
Object.defineProperty(exports, "BaseEntity", { enumerable: true, get: function () { return base_entity_1.BaseEntity; } });
var user_entity_1 = require("./user.entity");
Object.defineProperty(exports, "User", { enumerable: true, get: function () { return user_entity_1.User; } });
var role_entity_1 = require("./role.entity");
Object.defineProperty(exports, "Role", { enumerable: true, get: function () { return role_entity_1.Role; } });
var user_role_entity_1 = require("./user-role.entity");
Object.defineProperty(exports, "UserRole", { enumerable: true, get: function () { return user_role_entity_1.UserRole; } });
var agent_entity_1 = require("./agent.entity");
Object.defineProperty(exports, "Agent", { enumerable: true, get: function () { return agent_entity_1.Agent; } });
var admin_unit_entity_1 = require("./admin-unit.entity");
Object.defineProperty(exports, "AdminUnit", { enumerable: true, get: function () { return admin_unit_entity_1.AdminUnit; } });
var property_type_entity_1 = require("./property-type.entity");
Object.defineProperty(exports, "PropertyType", { enumerable: true, get: function () { return property_type_entity_1.PropertyType; } });
var listing_entity_1 = require("./listing.entity");
Object.defineProperty(exports, "Listing", { enumerable: true, get: function () { return listing_entity_1.Listing; } });
var lead_entity_1 = require("./lead.entity");
Object.defineProperty(exports, "Lead", { enumerable: true, get: function () { return lead_entity_1.Lead; } });
var deal_entity_1 = require("./deal.entity");
Object.defineProperty(exports, "Deal", { enumerable: true, get: function () { return deal_entity_1.Deal; } });
//# sourceMappingURL=index.js.map