import { AdminUnit } from '@realestate/database';

/**
 * Vietnam administrative units - 63 provinces/cities
 * Top-level only for MVP1 (provinces/cities)
 * Districts and wards can be seeded from database/seeds/vietnam_admin_units.sql
 */
export const adminUnitsSeed: Partial<AdminUnit>[] = [
  // Major cities (5 centrally governed cities)
  {
    code: '01',
    name: 'Thành phố Hà Nội',
    nameEn: 'Hanoi',
    level: 1,
    parentCode: null,
    isActive: true,
  },
  {
    code: '79',
    name: 'Thành phố Hồ Chí Minh',
    nameEn: 'Ho Chi Minh City',
    level: 1,
    parentCode: null,
    isActive: true,
  },
  {
    code: '48',
    name: 'Thành phố Đà Nẵng',
    nameEn: 'Da Nang',
    level: 1,
    parentCode: null,
    isActive: true,
  },
  {
    code: '31',
    name: 'Thành phố Hải Phòng',
    nameEn: 'Hai Phong',
    level: 1,
    parentCode: null,
    isActive: true,
  },
  {
    code: '92',
    name: 'Thành phố Cần Thơ',
    nameEn: 'Can Tho',
    level: 1,
    parentCode: null,
    isActive: true,
  },

  // Northern provinces
  {
    code: '02',
    name: 'Tỉnh Hà Giang',
    nameEn: 'Ha Giang',
    level: 1,
    parentCode: null,
    isActive: true,
  },
  {
    code: '04',
    name: 'Tỉnh Cao Bằng',
    nameEn: 'Cao Bang',
    level: 1,
    parentCode: null,
    isActive: true,
  },
  {
    code: '06',
    name: 'Tỉnh Bắc Kạn',
    nameEn: 'Bac Kan',
    level: 1,
    parentCode: null,
    isActive: true,
  },
  {
    code: '08',
    name: 'Tỉnh Tuyên Quang',
    nameEn: 'Tuyen Quang',
    level: 1,
    parentCode: null,
    isActive: true,
  },
  {
    code: '10',
    name: 'Tỉnh Lào Cai',
    nameEn: 'Lao Cai',
    level: 1,
    parentCode: null,
    isActive: true,
  },
  {
    code: '11',
    name: 'Tỉnh Điện Biên',
    nameEn: 'Dien Bien',
    level: 1,
    parentCode: null,
    isActive: true,
  },
  {
    code: '12',
    name: 'Tỉnh Lai Châu',
    nameEn: 'Lai Chau',
    level: 1,
    parentCode: null,
    isActive: true,
  },
  {
    code: '14',
    name: 'Tỉnh Sơn La',
    nameEn: 'Son La',
    level: 1,
    parentCode: null,
    isActive: true,
  },
  {
    code: '15',
    name: 'Tỉnh Yên Bái',
    nameEn: 'Yen Bai',
    level: 1,
    parentCode: null,
    isActive: true,
  },
  {
    code: '17',
    name: 'Tỉnh Hoà Bình',
    nameEn: 'Hoa Binh',
    level: 1,
    parentCode: null,
    isActive: true,
  },
  {
    code: '19',
    name: 'Tỉnh Thái Nguyên',
    nameEn: 'Thai Nguyen',
    level: 1,
    parentCode: null,
    isActive: true,
  },
  {
    code: '20',
    name: 'Tỉnh Lạng Sơn',
    nameEn: 'Lang Son',
    level: 1,
    parentCode: null,
    isActive: true,
  },
  {
    code: '22',
    name: 'Tỉnh Quảng Ninh',
    nameEn: 'Quang Ninh',
    level: 1,
    parentCode: null,
    isActive: true,
  },
  {
    code: '24',
    name: 'Tỉnh Bắc Giang',
    nameEn: 'Bac Giang',
    level: 1,
    parentCode: null,
    isActive: true,
  },
  {
    code: '25',
    name: 'Tỉnh Phú Thọ',
    nameEn: 'Phu Tho',
    level: 1,
    parentCode: null,
    isActive: true,
  },
  {
    code: '26',
    name: 'Tỉnh Vĩnh Phúc',
    nameEn: 'Vinh Phuc',
    level: 1,
    parentCode: null,
    isActive: true,
  },
  {
    code: '27',
    name: 'Tỉnh Bắc Ninh',
    nameEn: 'Bac Ninh',
    level: 1,
    parentCode: null,
    isActive: true,
  },
  {
    code: '30',
    name: 'Tỉnh Hải Dương',
    nameEn: 'Hai Duong',
    level: 1,
    parentCode: null,
    isActive: true,
  },
  {
    code: '33',
    name: 'Tỉnh Hưng Yên',
    nameEn: 'Hung Yen',
    level: 1,
    parentCode: null,
    isActive: true,
  },
  {
    code: '34',
    name: 'Tỉnh Thái Bình',
    nameEn: 'Thai Binh',
    level: 1,
    parentCode: null,
    isActive: true,
  },
  {
    code: '35',
    name: 'Tỉnh Hà Nam',
    nameEn: 'Ha Nam',
    level: 1,
    parentCode: null,
    isActive: true,
  },
  {
    code: '36',
    name: 'Tỉnh Nam Định',
    nameEn: 'Nam Dinh',
    level: 1,
    parentCode: null,
    isActive: true,
  },
  {
    code: '37',
    name: 'Tỉnh Ninh Bình',
    nameEn: 'Ninh Binh',
    level: 1,
    parentCode: null,
    isActive: true,
  },

  // Central provinces
  {
    code: '38',
    name: 'Tỉnh Thanh Hóa',
    nameEn: 'Thanh Hoa',
    level: 1,
    parentCode: null,
    isActive: true,
  },
  {
    code: '40',
    name: 'Tỉnh Nghệ An',
    nameEn: 'Nghe An',
    level: 1,
    parentCode: null,
    isActive: true,
  },
  {
    code: '42',
    name: 'Tỉnh Hà Tĩnh',
    nameEn: 'Ha Tinh',
    level: 1,
    parentCode: null,
    isActive: true,
  },
  {
    code: '44',
    name: 'Tỉnh Quảng Bình',
    nameEn: 'Quang Binh',
    level: 1,
    parentCode: null,
    isActive: true,
  },
  {
    code: '45',
    name: 'Tỉnh Quảng Trị',
    nameEn: 'Quang Tri',
    level: 1,
    parentCode: null,
    isActive: true,
  },
  {
    code: '46',
    name: 'Tỉnh Thừa Thiên Huế',
    nameEn: 'Thua Thien Hue',
    level: 1,
    parentCode: null,
    isActive: true,
  },
  {
    code: '49',
    name: 'Tỉnh Quảng Nam',
    nameEn: 'Quang Nam',
    level: 1,
    parentCode: null,
    isActive: true,
  },
  {
    code: '51',
    name: 'Tỉnh Quảng Ngãi',
    nameEn: 'Quang Ngai',
    level: 1,
    parentCode: null,
    isActive: true,
  },
  {
    code: '52',
    name: 'Tỉnh Bình Định',
    nameEn: 'Binh Dinh',
    level: 1,
    parentCode: null,
    isActive: true,
  },
  {
    code: '54',
    name: 'Tỉnh Phú Yên',
    nameEn: 'Phu Yen',
    level: 1,
    parentCode: null,
    isActive: true,
  },
  {
    code: '56',
    name: 'Tỉnh Khánh Hòa',
    nameEn: 'Khanh Hoa',
    level: 1,
    parentCode: null,
    isActive: true,
  },
  {
    code: '58',
    name: 'Tỉnh Ninh Thuận',
    nameEn: 'Ninh Thuan',
    level: 1,
    parentCode: null,
    isActive: true,
  },
  {
    code: '60',
    name: 'Tỉnh Bình Thuận',
    nameEn: 'Binh Thuan',
    level: 1,
    parentCode: null,
    isActive: true,
  },

  // Central Highlands
  {
    code: '62',
    name: 'Tỉnh Kon Tum',
    nameEn: 'Kon Tum',
    level: 1,
    parentCode: null,
    isActive: true,
  },
  {
    code: '64',
    name: 'Tỉnh Gia Lai',
    nameEn: 'Gia Lai',
    level: 1,
    parentCode: null,
    isActive: true,
  },
  {
    code: '66',
    name: 'Tỉnh Đắk Lắk',
    nameEn: 'Dak Lak',
    level: 1,
    parentCode: null,
    isActive: true,
  },
  {
    code: '67',
    name: 'Tỉnh Đắk Nông',
    nameEn: 'Dak Nong',
    level: 1,
    parentCode: null,
    isActive: true,
  },
  {
    code: '68',
    name: 'Tỉnh Lâm Đồng',
    nameEn: 'Lam Dong',
    level: 1,
    parentCode: null,
    isActive: true,
  },

  // Southern provinces
  {
    code: '70',
    name: 'Tỉnh Bình Phước',
    nameEn: 'Binh Phuoc',
    level: 1,
    parentCode: null,
    isActive: true,
  },
  {
    code: '72',
    name: 'Tỉnh Tây Ninh',
    nameEn: 'Tay Ninh',
    level: 1,
    parentCode: null,
    isActive: true,
  },
  {
    code: '74',
    name: 'Tỉnh Bình Dương',
    nameEn: 'Binh Duong',
    level: 1,
    parentCode: null,
    isActive: true,
  },
  {
    code: '75',
    name: 'Tỉnh Đồng Nai',
    nameEn: 'Dong Nai',
    level: 1,
    parentCode: null,
    isActive: true,
  },
  {
    code: '77',
    name: 'Tỉnh Bà Rịa - Vũng Tàu',
    nameEn: 'Ba Ria - Vung Tau',
    level: 1,
    parentCode: null,
    isActive: true,
  },
  {
    code: '80',
    name: 'Tỉnh Long An',
    nameEn: 'Long An',
    level: 1,
    parentCode: null,
    isActive: true,
  },
  {
    code: '82',
    name: 'Tỉnh Tiền Giang',
    nameEn: 'Tien Giang',
    level: 1,
    parentCode: null,
    isActive: true,
  },
  {
    code: '83',
    name: 'Tỉnh Bến Tre',
    nameEn: 'Ben Tre',
    level: 1,
    parentCode: null,
    isActive: true,
  },
  {
    code: '84',
    name: 'Tỉnh Trà Vinh',
    nameEn: 'Tra Vinh',
    level: 1,
    parentCode: null,
    isActive: true,
  },
  {
    code: '86',
    name: 'Tỉnh Vĩnh Long',
    nameEn: 'Vinh Long',
    level: 1,
    parentCode: null,
    isActive: true,
  },
  {
    code: '87',
    name: 'Tỉnh Đồng Tháp',
    nameEn: 'Dong Thap',
    level: 1,
    parentCode: null,
    isActive: true,
  },
  {
    code: '89',
    name: 'Tỉnh An Giang',
    nameEn: 'An Giang',
    level: 1,
    parentCode: null,
    isActive: true,
  },
  {
    code: '91',
    name: 'Tỉnh Kiên Giang',
    nameEn: 'Kien Giang',
    level: 1,
    parentCode: null,
    isActive: true,
  },
  {
    code: '93',
    name: 'Tỉnh Hậu Giang',
    nameEn: 'Hau Giang',
    level: 1,
    parentCode: null,
    isActive: true,
  },
  {
    code: '94',
    name: 'Tỉnh Sóc Trăng',
    nameEn: 'Soc Trang',
    level: 1,
    parentCode: null,
    isActive: true,
  },
  {
    code: '95',
    name: 'Tỉnh Bạc Liêu',
    nameEn: 'Bac Lieu',
    level: 1,
    parentCode: null,
    isActive: true,
  },
  {
    code: '96',
    name: 'Tỉnh Cà Mau',
    nameEn: 'Ca Mau',
    level: 1,
    parentCode: null,
    isActive: true,
  },
];
